In [3]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.ndim #number of axis

2

In [5]:
a.shape

(3, 5)

In [7]:
a.itemsize #size in byte of each element

8

In [8]:
a.size

15

## array creation

In [10]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [11]:
b.dtype

dtype('int64')

In [14]:
c=np.array([[2,3],[3,4]],dtype=complex)
c

array([[2.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2,3,4))#3d array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
np.empty((2,3))

array([[2.74681685e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [18]:
np.arange(10,30,5)

array([10, 15, 20, 25])

## printing arrays

In [19]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## basic operations

In [24]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c

array([20, 29, 38, 47])

In [25]:
b**2

array([0, 1, 4, 9])

In [26]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [27]:
a<35

array([ True,  True, False, False])

2d

In [29]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
a*b

array([[2, 0],
       [0, 4]])

In [30]:
a@b #matrix product

array([[5, 4],
       [3, 4]])

In [31]:
a.dot(b) #matrix product

array([[5, 4],
       [3, 4]])

In [33]:
a=np.ones((2,3),dtype=int)
a=a*3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [36]:
b=np.linspace(0,3.14,3)#returns evenly spaced numbers over a specific interval
b

array([0.  , 1.57, 3.14])

In [39]:
a=np.random.random((2,3))
a

array([[0.46647026, 0.66849524, 0.23614386],
       [0.82025514, 0.37381643, 0.83384637]])

In [40]:
a.sum(axis=0)#columns

array([1.2867254 , 1.04231167, 1.06999024])

In [41]:
a.sum(axis=1)#rows

array([1.37110937, 2.02791794])

## universal fn

In [42]:
np.exp(b)

array([ 1.        ,  4.80664819, 23.10386686])

In [43]:
b

array([0.  , 1.57, 3.14])

In [44]:
np.sqrt(b)

array([0.        , 1.25299641, 1.77200451])

## multidimensional array

In [45]:
def f(x,y):
  return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [46]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [47]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## shape manipulation

In [49]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [50]:
b.reshape(4,5)

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

In [51]:
b.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [53]:
b.T.shape

(4, 5)

## linear algebra

In [56]:
a=np.array([[1,2],[3,4]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [57]:
u=np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [58]:
np.trace(u)#sum of diagonals

2.0

In [59]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))